### ISSUE TITLE
avatar parameters saverがレポジトリの不具合でインストールできない

### ISSUE THREAD

**Issue by ni1chigo2115** [Narazaka/vpm-repos#1]
タイトル通りです

**Comment by Narazaka** [comment]
@ni1chigo2115 報告ありがとうございます。

リポジトリ自体は仕様に準拠した作りになっている（「リポジトリの不具合」ではない）んですが、vpm-resolver側の不具合で場合によってインストールできないようでした……（なぜかインストール出来る人と出来ない人が居る）。
https://github.com/vrchat-community/creator-companion/issues/29#issuecomment-1713205625

ワークアラウンドとして一部バージョン指定を除外したので2.1.1が多分インストールできるはずです
